### ISSUE TITLE
NPE when opening rule-detail-edit.xml

### ISSUE THREAD

**Issue by IskandarovRost** [adhawan325/cuba-duplicate-tools-addon#1]
1) create a new Rule
2) fill required fields
3) create a new RuleDetail

AR: NPE 
```code

java.lang.NullPointerException
    at com.non.dta.web.ruledetail.RuleDetailEdit.postInit(RuleDetailEdit.java:52)
    at com.haulmont.cuba.gui.components.AbstractEditor.setItem(AbstractEditor.java:72)
    at com.haulmont.cuba.gui.WindowManager.openEditor(WindowManager.java:893)
    at com.haulmont.cuba.web.WebWindowManager.openEditor(WebWindowManager.java:178)
```

**Comment by adhawan325** [comment]
@IskandarovRost - This should be fixed.

**Comment by sedoc001** [comment]
This Issues is not fixed. Still getting the same error.
