### ISSUE TITLE
NULL pointer exception error

### ISSUE THREAD

**Issue by sedoc001** [adhawan325/cuba-duplicate-tools-addon#5]
I followed all the steps as described, but i'm getting a npe error. Same as in one of the closed issue's.

java.lang.NullPointerException
	at com.non.dta.service.DuplicateRuleServiceBean.findDuplicateEntityByQuery(DuplicateRuleServiceBean.java:106)
	at com.non.dta.service.DuplicateRuleServiceBean.checkIfDuplicate(DuplicateRuleServiceBean.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by adhawan325** [comment]
Send me the version of platform you are using and full stack trace please. 

Thanks. 


On Jan 23, 2020, at 2:02 PM, sedoc001 <notifications@github.com> wrote:

﻿

I followed all the steps as described, but i'm getting a npe error. Same as in one of the closed issue's.

**Comment by sedoc001** [comment]
Cuba version 6.10.9
I don't know how to perform a full stack trace.

**Comment by adhawan325** [comment]
Please share exact steps you followed.  I am able to use the extension on the version you mentioned. 

Thanks. 


On Jan 24, 2020, at 6:12 PM, sedoc001 <notifications@github.com> wrote:

﻿

Cuba version 6.10.9
I don't know how to perform a full stack trace.

**Comment by sedoc001** [comment]
1. I add the component to my project
2. restarted the prjoject
3. set the rule for one entity, where base and matching entity are the same. Also base record field and matching record field are the same.

**Comment by sedoc001** [comment]
![duplicate detection](https://user-images.githubusercontent.com/18465674/73289443-7bddd400-41db-11ea-914e-593bb3562bd9.PNG)

**Comment by sedoc001** [comment]
i accidently closed the issue.
